#!/usr/bin/env node

/* eslint-disable */

var exec = require('child_process').exec;
var path = require('path');
var fs   = require('fs');

process.stdin.resume();
process.stdin.setEncoding('utf8');

// __dirname always is the name of the directory this script sits in, see https://stackoverflow.com/questions/8131344/what-is-the-difference-between-dirname-and-in-node-js
var dir = path.join(__dirname, '..');


  installDeps(function(error) {
    if (error) {
      process.stdout.write(error);
    }
    deleteFileInCurrentDir('contribute', function(error) {
      if (error) {
        process.stdout.write(error);
      }
    });
  });



/**
 * Deletes a file in the current directory
 */
function deleteFileInCurrentDir(file, callback) {
  fs.unlink(path.join(__dirname, file), callback);
}

/**
 * Installs dependencies
 */
function installDeps(callback) {
  process.stdout.write('\nInstalling dependencies... (This might take a while)')
  exec('npm install', addCheckMark.bind(null, callback));
}

/**
 * Adds mark check symbol
 */
function addCheckMark(callback) {
  process.stdout.write(' ✓');
  callback();
}
